typography_spectrum: 0.38385
color:
  brandColors:
    - '#e3441f'
    - '#ffffff'
    - '#171416'
    - '#773520'
    - '#b1b1b1'
  brandStrength: 0.1875
  lightness: 0.5480225929059088
  saturation: 0.9848919552750885
  rhythmicContrast: 0.8383568830322474
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.99258
analytics:
  google: null
  facebook: null
  twitter: null
name: Ludically
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Ludically
description: Boardgames
purpose: []
