typography_spectrum: 0.38385
color:
  brandColors:
    - '#e3441f'
    - '#ffffff'
    - '#171416'
    - '#773520'
    - '#b1b1b1'
  brandStrength: 0.1875
  lightness: 0.5480225929059088
  saturation: 0.9848919552750885
  rhythmicContrast: 0.8383568830322474
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.99258
analytics:
  google: null
  facebook: null
  twitter: null
name: Ludically
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Bandes Dessinées
    id: 22906edb-2c89-4e92-b9c7-e6feca41b5f5
    type: content
  - name: 4 Gods
    id: 5dc2a2f5-707d-4fd8-b6b6-0d6d50c2f5e1
    type: content
favicon: null
title: Ludically
description: Boardgames
purpose: []
