name: Ludically
favicon: null
layout_spectrum: 0.10899337660521269
typography_spectrum: 0.5617195481900126
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.0940492779482156
  lightness: 0.5480225929059088
  saturation: 0.9848919552750885
  rhythmicContrast: 0.8383568830322474
purpose: []
